# Generated by Django 5.0.6 on 2024-06-14 17:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musicians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('release_date', models.DateField(default=datetime.date.today)),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Album', to='musicians.musician')),
            ],
        ),
    ]
